"""delete column refresh_token_jti from users

Revision ID: 27c332fd607a
Revises: e87dfdd5313c
Create Date: 2025-11-17 14:41:31.147473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c332fd607a'
down_revision = 'e87dfdd5313c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_refresh_token_jti')
        batch_op.drop_column('refresh_token_jti')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_jti', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index('ix_users_refresh_token_jti', ['refresh_token_jti'], unique=False)

    # ### end Alembic commands ###
