"""empty message

Revision ID: 46a39be636c7
Revises: 857a81b35aaf
Create Date: 2025-11-27 11:48:50.780942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a39be636c7'
down_revision = '857a81b35aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlocked_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('learning_topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['learning_topic_id'], ['learning_topics.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_topic_id', name='unique_user_topic_unlock')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unlocked_topics')
    # ### end Alembic commands ###
