"""empty message

Revision ID: 4fcf9f258190
Revises: 46a39be636c7
Create Date: 2025-11-27 12:03:28.883096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcf9f258190'
down_revision = '46a39be636c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unique_level_difficulty', type_='unique')
        batch_op.create_unique_constraint('unique_lang_level_difficulty', ['language_id', 'level_id', 'difficulty'])
        batch_op.create_foreign_key('fk_learning_topics_language_id', 'languages', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_learning_topics_language_id', type_='foreignkey')
        batch_op.drop_constraint('unique_lang_level_difficulty', type_='unique')
        batch_op.create_unique_constraint('unique_level_difficulty', ['level_id', 'difficulty'])
        batch_op.drop_column('language_id')

    # ### end Alembic commands ###
