"""empty message

Revision ID: 857a81b35aaf
Revises: a46f3624b735
Create Date: 2025-11-27 11:30:49.896518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857a81b35aaf'
down_revision = 'a46f3624b735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'difficulty', name='unique_level_difficulty')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_topics')
    # ### end Alembic commands ###
