"""empty message

Revision ID: a2179c6004af
Revises: 4fcf9f258190
Create Date: 2025-11-27 14:08:13.025718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2179c6004af'
down_revision = '4fcf9f258190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unlocked_topics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlocked_topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('level_id', sa.INTEGER(), nullable=False),
    sa.Column('learning_topic_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['learning_topic_id'], ['learning_topics.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_topic_id', name='unique_user_topic_unlock')
    )
    # ### end Alembic commands ###
