"""empty message

Revision ID: cd85892cc7ee
Revises: a8f1953f5a94
Create Date: 2026-01-14 14:11:33.000955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd85892cc7ee'
down_revision = 'a8f1953f5a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_topic_id', sa.Integer(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('question_statement', sa.Text(), nullable=False),
    sa.Column('choices', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['learning_topic_id'], ['learning_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_histories')
    # ### end Alembic commands ###
