"""empty message

Revision ID: e6e649866557
Revises: 2a90fd2bbe00
Create Date: 2026-01-13 14:17:57.441125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e649866557'
down_revision = '2a90fd2bbe00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_key', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_topics', schema=None) as batch_op:
        batch_op.drop_column('topic_key')

    # ### end Alembic commands ###
